DROP TABLE IF EXISTS commons cascade;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS suppliers;
DROP TABLE IF EXISTS authors;
DROP TYPE IF EXISTS role;
DROP TABLE IF EXISTS c_groups;
DROP TABLE IF EXISTS contracts;