services:
    backend:
      build:
        context: backend
        target: builder
      container_name: b-ps-app
      ports:
        - "8000:8000"
      depends_on:
        - db
      networks:
        - net

    db:
      image: postgres:alpine
      container_name: db-ps-psql
      volumes:
        - db-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB="test_db"
        - POSTGRES_user="postgres"
        - POSTGRES_PASSWORD="1234qwER"
      expose:
        - 5432
      networks:
        - net

networks:
  net:
    name: net

volumes:
  db-data:
