### Send POST request with json body
POST http://127.0.0.1:8080/documents/add
Content-Type: application/json

### Send POST request with json body
POST http://127.0.0.1:8080/documents/1
Content-Type: application/json