### Send POST request with json body
POST http://127.0.0.1:8888/documents/add
Content-Type: application/json

{
  "id": 3,
  "name": "NEW GK",
  "date": "2023-01-28T15:04:05Z",
  "description": "new descriptions",
  "file": "",
  "date_in": "2023-01-01T15:04:05Z",
  "date_out": "2023-12-31T00:00:00Z",
  "distributor": "mts",
  "method": "аукцион",
  "sum": 1000.90
}


### Send UPDATE request with json body
PATCH http://127.0.0.1:8080/documents/update/3
Content-Type: application/json

{
  "id": 33,
  "name": "NEW GK 3 update",
  "date": "2023-01-28T15:04:05Z",
  "description": "new descriptions",
  "file": "",
  "date_in": "2023-01-01T15:04:05Z",
  "date_out": "2023-12-31T00:00:00Z",
  "distributor": "mts",
  "method": "аукцион",
  "sum": 1200.90
}

### Send DELETE by ID
DELETE http://127.0.0.1:8080/documents/delete/1

### Send DELETES ALL 
DELETE http://127.0.0.1:8080/documents/delete