DROP TABLE IF EXISTS commons cascade;
DROP TABLE IF EXISTS categories ;
DROP TABLE IF EXISTS suppliers ;
DROP TABLE IF EXISTS authors ;
DROP TABLE IF EXISTS c_groups ;
DROP TABLE IF EXISTS contracts ;